# lightning.pytorch==2.0.0
seed_everything: 0
trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: 'satclip_logs'
      name: 'satclip-greater-seattle'
      version: '2'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        save_last: True
        filename: "{epoch}-{val_loss:.2f}"
  max_epochs: 10
  accumulate_grad_batches: 1
  log_every_n_steps: 5
model:
  embed_dim: 256
  image_resolution: 256
  vision_layers: 'moco_resnet18_4band'
  vision_width: 64
  vision_patch_size: 8
  in_channels: 4
  le_type: 'theory'
  pe_type: 'siren'
  frequency_num: 16
  max_radius: 1.0
  min_radius: 0.02
  legendre_polys: 32
  sh_embedding_dims: 32
  learning_rate: 0.0001
  num_hidden_layers: 2
  capacity: 256
data:
  data_dir: 
  train_data_dir: /content/drive/MyDrive/PHYS 417/data/sent2_1x1km/train/images
  val_data_dir: /content/drive/MyDrive/PHYS 417/data/sent2_1x1km/val_test/images
  train_csv: /content/drive/MyDrive/PHYS 417/data/sent2_1x1km/train/index.csv
  val_csv: /content/drive/MyDrive/PHYS 417/data/sent2_1x1km/val_test/index_val.csv
  batch_size: 256
  num_workers: 8
  crop_size: 256
  transform: 'normalized'
watchmodel: True
